name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm ci
      
      - name: Run quality checks
        run: |
          npm audit --audit-level=high
          node -c index.js
          node -c nodes/metrics-node.js
          node -c lib/metrics-collector.js
          node -c lib/node-red-hooks.js
          node -c lib/prometheus-exporter.js
          npm pack --dry-run
      
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}